version: 2
updates:
    directory: '/' # Look for package.json in the root directory
    open-pull-requests-limit: 5
    schedule:
      interval: 'daily'
      time: '10:00'
      timezone: 'Europe/Berlin'
    assignees: ['born3am']
    commit-message:
      prefix: 'chore' # PR title prefix
      include: 'scope' # Include scope in PR title
    groups:
      minor-updates: # Group all patch updates together
        applies-to: 'version-updates' # version-updates or security-updates
        update-types:
          - 'patch'
    versioning-strategy: increase-if-necessary # Only bump version if required for compatibility or security
    ignore:
      - dependency-name: '*' # Ignore all pre-release versions for stability
        versions:
        - 'alpha' # Unstable early-stage development versions
        - 'beta' # Pre-production versions
        - 'canary' # Frequently updated testing versions
        - 'dev' # Developer-only versions
        - 'experimental' # Experimental versions with high instability
        - 'legacy' # Deprecated versions
        - 'next' # Future versions not finalized
        - 'nightly' # Daily unstable builds
        